app/models.py
from flask_sqlalchemy import  SQLAlchemy
from flask import  url_for

db= SQLAlchemy()

### define any model here


class Student(db.Model):
    __tablename__ = 'students'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    image = db.Column(db.String(100), nullable=True)
    grade = db.Column(db.Integer, nullable=True)
    age = db.Column(db.Integer, nullable=True)


    def __str__(self):
        return f"{self.name}"

    @property
    def image_url(self):
        return url_for('static', filename=f"students/images/{self.image}")

    @property
    def show_url(self):
        return url_for('students.show', id=self.id)

    @property
    def delete_url(self):
        return url_for('students.delete', id=self.id)

app/__init__.py
from flask import Flask

""" call config options"""
from app.config import config_options  # dict

""" call db object from models file """
from app.models import db

""" use migrate """
from flask_migrate import Migrate

# 1- create app
def create_app(config_name='prd'):

    app = Flask(__name__)

    current_config = config_options[config_name]  # Class of config
    # configure app with db. ,
    print(current_config)
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config.SQLALCHEMY_DATABASE_URI
    # another way
    app.config.from_object(current_config)  # read need config. for app from the given class

    # Connect db object with app
    db.init_app(app)


    "add migrate to the project "
    migrate = Migrate(app, db)

    """ next I need to initialize migration directory
        then generate migration files
        
        go terminal
        cd app 
        export FLASK_APP=flasky
        flask db init  # generate migration directory
        # to generate migration files
        flask db migrate  -m 'create students table'
        # to apply migration 
        flask db upgrade 
        
    """

    # register url
    # from app.students.views import  index
    # app.add_url_rule("/students", view_func=index , endpoint='students.index')

    # I need to ask app to use ?? blueprint
    from app.students import student_blueprint
    app.register_blueprint(student_blueprint)




    return app

app/students/__init__.py
from flask import  Blueprint

# define blueprint for this app >?
# apply this on any route == url uses this blueprint
student_blueprint = Blueprint('students', __name__, url_prefix='/students')

from app.students import  views

app/students/views.py
from crypt import methods

from app.models import Student, db
from flask import render_template, request, redirect, url_for
from app.students import  student_blueprint

# use blueprint

@student_blueprint.route("", endpoint="index") # generated url /students
def index():
    students = Student.query.all()
    return render_template("students/index.html", students=students)


@student_blueprint.route("<int:id>", endpoint="show")
def show(id):
    student = db.get_or_404(Student, id)
    return  render_template("students/show.html", student=student)


@student_blueprint.route("create", endpoint="create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        student = Student(name=request.form["name"], grade=request.form["grade"], image=request.form["image"])
        db.session.add(student)
        db.session.commit()
        # return redirect(url_for("students.index"))
        return redirect(student.show_url)


    return render_template("students/create.html")



@student_blueprint.route("<int:id>/delete", endpoint="delete", methods=['POST'])
def delete(id):
    student = db.get_or_404(Student, id)
    db.session.delete(student)
    db.session.commit()
    return redirect(url_for("students.index"))


# add route for edit --> complete the logic

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('students.index')}}">Students</a>
        </li>
       <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('students.create')}}">Add student </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

      </ul>

    </div>
  </div>
</nav>

<div class="container">
    {% block main %}

    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

app/templates/students/create.html
{% extends './base.html' %}

{% block main %}
  <h1 style="text-align: center"> Add new Student</h1>

<form method="post">
  <div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" name="name" class="form-control" aria-describedby="emailHelp">
  </div>
 <div class="mb-3">
    <label class="form-label">Image</label>
    <input type="text" name="image" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label class="form-label">Grade</label>
    <input type="number" name="grade" class="form-control" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

app/templates/students/index.html
{% extends 'base.html' %}

{% block main %}
    <h1> All Students </h1>
    <table class="table">
        <tr> <th> ID</th> <th> Name </th>
            <th> Image</th> <td>Show</td> <td>Delete</td>
        </tr>

        {% for student in students %}
            <tr>
                <td>{{student.id}}</td>
                <td> {{student.name}}</td>
                <td> <img src="{{student.image_url}}" width="100" height="100"> </td>
                <td> <a href="{{student.show_url}}" class="btn btn-info">Show </a> </td>
<!--                <td> <a href="{{student.delete_url}}" class="btn btn-danger">Delete </a> </td>-->
                <td>
                    <form action="{{student.delete_url}}" method="post">
                        <input type="submit" value="Delete" class="btn btn-danger">
                    </form>
                </td>
            </tr>

        {% endfor %}

    </table>


{% endblock %}

app/templates/students/show.html
{% extends './base.html' %}

{% block main %}

    <h1> Student Info </h1>
<div class="card" style="width: 18rem;">

  <img src="{{student.image_url}}"  class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{student.name}}</h5>
    <p class="card-text">{{student.grade}}</p>
    <a href="{{ url_for('students.index')}}" class="btn btn-primary">Back to all Students</a>
  </div>
</div>

{% endblock %}